// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fniivhoryfgxlsdaqlfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuaWl2aG9yeWZneGxzZGFxbGZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDE4OTMsImV4cCI6MjA2Njk3Nzg5M30.U_j8DuXURujLu1TM151cyTOeaTcTHazOcNJ937KcI7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});